version: '3.8'

services:
  backend:
    image: girasakpsdev/mern-backend:latest
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/inventory
    depends_on:
      - mongo

  frontend:
    image: girasakpsdev/mern-frontend:latest
    container_name: mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mern-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: